### PR TITLE
Added Playertest cases and also made some changes in the player class

### PR DESCRIPTION
**Pull request by ayaney85**
Shivani and Quan, please review the changes and let me know if I can merge it in. Thanks!

### CODE REVIEW

**Review by quannytsunami — APPROVED** [review]
Test cases - 4/4. No merge conflicts. Review approved.
testPlayer1 --> Pass
testPlayer2 --> Pass. Was it intentional to call the test case "testPlayer2()", but declared "player1" object within the test case? 
testsetPlayerChipCount --> Pass
testPlayerString --> Pass

Player.java --> No merge conflicts and will compile. Review approved.

**Comment by ayaney85** [comment]
Thanks for the review Quan and as for your question: testPlayer2 --> Pass. Was it intentional to call the test case "testPlayer2()", but declared "player1" object within the test case? -> yes! I will see if I can make some changes to that test case so that it makes sense. T

**Comment by ayaney85** [comment]
Squash and merge Ayan's changes to the Player class plus TestPlayer class

**Comment by ayaney85** [comment]
Squash and merge Ayan's changes to the Player class plus TestPlayer class

**Pull request merged**
